import { createElement, type ComponentProps } from "react";
import {
  Baby,
  Banknote,
  Beer,
  Bike,
  BookOpen,
  Briefcase,
  Building2,
  Bus,
  Car,
  CarTaxiFront,
  Cigarette,
  Coffee,
  Coins,
  CreditCard,
  Droplet,
  Dumbbell,
  Ellipsis,
  Film,
  Fuel,
  Gamepad2,
  Gift,
  Globe,
  GraduationCap,
  HandHeart,
  HandCoins,
  Hammer,
  HeartPulse,
  House,
  Landmark,
  Laptop,
  Music,
  Palette,
  PawPrint,
  Percent,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Popcorn,
  Receipt,
  Repeat,
  Scissors,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sofa,
  Sparkles,
  Stethoscope,
  Toothbrush,
  TrainFront,
  TreePine,
  TrendingUp,
  Tv,
  Umbrella,
  Utensils,
  Wallet,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

import { Boy, ChocolateBar, Tooth, YoungMan } from "@/lib/custom-icons";

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  "shopping-cart": ShoppingCart,
  utensils: Utensils,
  coffee: Coffee,
  pizza: Pizza,
  chocolate: ChocolateBar,
  beer: Beer,
  bus: Bus,
  "train-front": TrainFront,
  car: Car,
  "car-taxi-front": CarTaxiFront,
  fuel: Fuel,
  bike: Bike,
  plane: Plane,
  house: House,
  "building-2": Building2,
  sofa: Sofa,
  zap: Zap,
  droplet: Droplet,
  wrench: Wrench,
  hammer: Hammer,
  "heart-pulse": HeartPulse,
  pill: Pill,
  stethoscope: Stethoscope,
  tooth: Tooth,
  toothbrush: Toothbrush,
  dumbbell: Dumbbell,
  popcorn: Popcorn,
  film: Film,
  "gamepad-2": Gamepad2,
  music: Music,
  tv: Tv,
  palette: Palette,
  "shopping-bag": ShoppingBag,
  shirt: Shirt,
  sparkles: Sparkles,
  scissors: Scissors,
  wifi: Wifi,
  smartphone: Smartphone,
  laptop: Laptop,
  repeat: Repeat,
  "graduation-cap": GraduationCap,
  "book-open": BookOpen,
  baby: Baby,
  boy: Boy,
  "young-man": YoungMan,
  "paw-print": PawPrint,
  gift: Gift,
  "hand-heart": HandHeart,
  "tree-pine": TreePine,
  umbrella: Umbrella,
  globe: Globe,
  cigarette: Cigarette,
  receipt: Receipt,
  "credit-card": CreditCard,
  landmark: Landmark,
  briefcase: Briefcase,
  "hand-coins": HandCoins,
  banknote: Banknote,
  coins: Coins,
  wallet: Wallet,
  "piggy-bank": PiggyBank,
  percent: Percent,
  "trending-up": TrendingUp,
  ellipsis: Ellipsis,
};

export const CATEGORY_ICON_NAMES = Object.keys(CATEGORY_ICONS);

export function getCategoryIcon(name: string): LucideIcon {
  return CATEGORY_ICONS[name] ?? Ellipsis;
}

/** Иконка категории по имени. createElement — чтобы не создавать компонент во время рендера. */
export function CategoryIcon({ name, ...props }: { name: string } & ComponentProps<LucideIcon>) {
  return createElement(getCategoryIcon(name), props);
}
